### ISSUE TITLE
[BUG] Something is causing a crash

### ISSUE THREAD

**Issue by NotExpectedYet** [NotExpectedYet/OctoFarm#181]
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39: TypeError: Cannot read property 'length' of undefined
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/server_src/lib/dataFunctions/printerClean.js:1068:46
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/node_modules/mongoose/lib/model.js:4843:16
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/node_modules/mongoose/lib/helpers/promiseOrCallback.js:16:11
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/node_modules/mongoose/lib/model.js:4866:21
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/node_modules/mongoose/lib/query.js:4402:18
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/node_modules/mongoose/lib/query.js:4437:14
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at cb (/app/node_modules/mongoose/lib/query.js:1926:14)
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:665:9
today at 12:48 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at handleCallback (/app/node_modules/mongoose/node_modules/mongodb/lib/utils.js:102:55)
today at 12:49 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/node_modules/mongoose/node_modules/mongodb/lib/cursor.js:834:20
today at 12:49 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at /app/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:736:9
today at 12:49 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at Object.callback (/app/node_modules/mongoose/node_modules/mongodb/lib/core/cursor.js:432:11)
today at 12:49 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at Timeout._onTimeout (/app/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/topology.js:443:25)
today at 12:49 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at listOnTimeout (internal/timers.js:531:17)
today at 12:49 12:48:39 0|OctoFarm  | 2020-11-09T12:48:39:     at processTimers (internal/timers.js:475:7)

**Comment by NotExpectedYet** [comment]
I'll take a look at the logs in the morning for you I'm about to go to bed. 

One thing. Nodejs 14 isn't supported, I only support the LTS version of. 12 is recommended. There are funnily enough database issues with 14 as well so worth a try until I can look at the logs.

**Comment by NotExpectedYet** [comment]
arm  | 2020-11-23T16:14:30: { i: '5f9168d10cc4e10014fe0b3f' }
today at 17:13 17:13:04 0|OctoFarm  | 2020-11-23T17:13:04: SyntaxError: Unexpected token u in JSON at position 0
today at 17:13 17:13:04 0|OctoFarm  | 2020-11-23T17:13:04:     at JSON.parse (<anonymous>)
today at 17:13 17:13:04 0|OctoFarm  | 2020-11-23T17:13:04:     at Timeout._onTimeout (/app/server_src/runners/state.js:697:34)
today at 17:13 17:13:04 0|OctoFarm  | 2020-11-23T17:13:04:     at listOnTimeout (internal/timers.js:531:17)
today at 17:13 17:13:04 0|OctoFarm  | 2020-11-23T17:13:04:     at processTimers (internal/timers.js:475:7)
